# permissions for end users to edit myapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: myapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: myapp-operator
    app.kubernetes.io/part-of: myapp-operator
    app.kubernetes.io/managed-by: kustomize
  name: myapp-editor-role
rules:
- apiGroups:
  - apps.leon.com
  resources:
  - myapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.leon.com
  resources:
  - myapps/status
  verbs:
  - get
